# coding: utf-8

"""
    License Management System

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.licenses_api import LicensesApi


class TestLicensesApi(unittest.TestCase):
    """LicensesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LicensesApi()

    def tearDown(self) -> None:
        pass

    def test_block_license_api_v1_licenses_license_id_block_post(self) -> None:
        """Test case for block_license_api_v1_licenses_license_id_block_post

        Block License
        """
        pass

    def test_create_license_api_v1_licenses_post(self) -> None:
        """Test case for create_license_api_v1_licenses_post

        Create License
        """
        pass

    def test_delete_license_api_v1_licenses_license_id_delete(self) -> None:
        """Test case for delete_license_api_v1_licenses_license_id_delete

        Delete License
        """
        pass

    def test_get_license_api_v1_licenses_license_id_get(self) -> None:
        """Test case for get_license_api_v1_licenses_license_id_get

        Get License
        """
        pass

    def test_list_licenses_api_v1_licenses_get(self) -> None:
        """Test case for list_licenses_api_v1_licenses_get

        List Licenses
        """
        pass

    def test_unblock_license_api_v1_licenses_license_id_unblock_post(self) -> None:
        """Test case for unblock_license_api_v1_licenses_license_id_unblock_post

        Unblock License
        """
        pass

    def test_update_license_api_v1_licenses_license_id_put(self) -> None:
        """Test case for update_license_api_v1_licenses_license_id_put

        Update License
        """
        pass


if __name__ == '__main__':
    unittest.main()
