# coding: utf-8

"""
    License Management System

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.license_key_create import LicenseKeyCreate

class TestLicenseKeyCreate(unittest.TestCase):
    """LicenseKeyCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LicenseKeyCreate:
        """Test LicenseKeyCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LicenseKeyCreate`
        """
        model = LicenseKeyCreate()
        if include_optional:
            return LicenseKeyCreate(
                customer_id = 56,
                application_id = 56,
                expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                max_activations = 56,
                features = None,
                notes = ''
            )
        else:
            return LicenseKeyCreate(
                customer_id = 56,
                application_id = 56,
        )
        """

    def testLicenseKeyCreate(self):
        """Test LicenseKeyCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
