# coding: utf-8

"""
    License Management System

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.token_scope import TokenScope

class TestTokenScope(unittest.TestCase):
    """TokenScope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTokenScope(self):
        """Test TokenScope"""
        # inst = TokenScope()

if __name__ == '__main__':
    unittest.main()
