# coding: utf-8

"""
    License Management System

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.authentication_api import AuthenticationApi


class TestAuthenticationApi(unittest.TestCase):
    """AuthenticationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthenticationApi()

    def tearDown(self) -> None:
        pass

    def test_change_password_api_v1_auth_change_password_post(self) -> None:
        """Test case for change_password_api_v1_auth_change_password_post

        Change Password
        """
        pass

    def test_create_api_token_api_v1_auth_tokens_post(self) -> None:
        """Test case for create_api_token_api_v1_auth_tokens_post

        Create Api Token
        """
        pass

    def test_create_user_api_v1_auth_users_post(self) -> None:
        """Test case for create_user_api_v1_auth_users_post

        Create User
        """
        pass

    def test_delete_api_token_api_v1_auth_tokens_token_id_delete(self) -> None:
        """Test case for delete_api_token_api_v1_auth_tokens_token_id_delete

        Delete Api Token
        """
        pass

    def test_get_all_users_api_v1_auth_users_get(self) -> None:
        """Test case for get_all_users_api_v1_auth_users_get

        Get All Users
        """
        pass

    def test_get_current_user_info_api_v1_auth_me_get(self) -> None:
        """Test case for get_current_user_info_api_v1_auth_me_get

        Get Current User Info
        """
        pass

    def test_get_user_api_v1_auth_users_user_id_get(self) -> None:
        """Test case for get_user_api_v1_auth_users_user_id_get

        Get User
        """
        pass

    def test_list_api_tokens_api_v1_auth_tokens_get(self) -> None:
        """Test case for list_api_tokens_api_v1_auth_tokens_get

        List Api Tokens
        """
        pass

    def test_login_api_v1_auth_login_post(self) -> None:
        """Test case for login_api_v1_auth_login_post

        Login
        """
        pass

    def test_patch_api_token_api_v1_auth_tokens_token_id_patch(self) -> None:
        """Test case for patch_api_token_api_v1_auth_tokens_token_id_patch

        Patch Api Token
        """
        pass

    def test_register_api_v1_auth_register_post(self) -> None:
        """Test case for register_api_v1_auth_register_post

        Register
        """
        pass

    def test_update_api_token_api_v1_auth_tokens_token_id_put(self) -> None:
        """Test case for update_api_token_api_v1_auth_tokens_token_id_put

        Update Api Token
        """
        pass

    def test_update_user_api_v1_auth_users_user_id_put(self) -> None:
        """Test case for update_user_api_v1_auth_users_user_id_put

        Update User
        """
        pass

    def test_update_user_business_role_api_v1_auth_users_user_id_business_role_put(self) -> None:
        """Test case for update_user_business_role_api_v1_auth_users_user_id_business_role_put

        Update User Business Role
        """
        pass

    def test_update_user_system_role_api_v1_auth_users_user_id_system_role_put(self) -> None:
        """Test case for update_user_system_role_api_v1_auth_users_user_id_system_role_put

        Update User System Role
        """
        pass


if __name__ == '__main__':
    unittest.main()
