# coding: utf-8

"""
    License Management System

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.api_token_create_response import APITokenCreateResponse

class TestAPITokenCreateResponse(unittest.TestCase):
    """APITokenCreateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> APITokenCreateResponse:
        """Test APITokenCreateResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `APITokenCreateResponse`
        """
        model = APITokenCreateResponse()
        if include_optional:
            return APITokenCreateResponse(
                id = 56,
                name = '',
                scopes = [
                    'license:read'
                    ],
                is_active = True,
                expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                token = ''
            )
        else:
            return APITokenCreateResponse(
                id = 56,
                name = '',
                scopes = [
                    'license:read'
                    ],
                is_active = True,
                expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                token = '',
        )
        """

    def testAPITokenCreateResponse(self):
        """Test APITokenCreateResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
