# coding: utf-8

"""
    License Management System

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.license_status import LicenseStatus

class TestLicenseStatus(unittest.TestCase):
    """LicenseStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLicenseStatus(self):
        """Test LicenseStatus"""
        # inst = LicenseStatus()

if __name__ == '__main__':
    unittest.main()
