# coding: utf-8

"""
    License Management System

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.activation_form_complete import ActivationFormComplete

class TestActivationFormComplete(unittest.TestCase):
    """ActivationFormComplete unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ActivationFormComplete:
        """Test ActivationFormComplete
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ActivationFormComplete`
        """
        model = ActivationFormComplete()
        if include_optional:
            return ActivationFormComplete(
                request_code = '',
                activation_code = ''
            )
        else:
            return ActivationFormComplete(
                request_code = '',
                activation_code = '',
        )
        """

    def testActivationFormComplete(self):
        """Test ActivationFormComplete"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
