# coding: utf-8

"""
    License Management System

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.user_business_role_update import UserBusinessRoleUpdate

class TestUserBusinessRoleUpdate(unittest.TestCase):
    """UserBusinessRoleUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserBusinessRoleUpdate:
        """Test UserBusinessRoleUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserBusinessRoleUpdate`
        """
        model = UserBusinessRoleUpdate()
        if include_optional:
            return UserBusinessRoleUpdate(
                business_role = 'user'
            )
        else:
            return UserBusinessRoleUpdate(
                business_role = 'user',
        )
        """

    def testUserBusinessRoleUpdate(self):
        """Test UserBusinessRoleUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
