# coding: utf-8

"""
    License Management System

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.license_validation_response import LicenseValidationResponse

class TestLicenseValidationResponse(unittest.TestCase):
    """LicenseValidationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LicenseValidationResponse:
        """Test LicenseValidationResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LicenseValidationResponse`
        """
        model = LicenseValidationResponse()
        if include_optional:
            return LicenseValidationResponse(
                valid = True,
                license_id = 56,
                customer_id = 56,
                application_id = 56,
                status = 'active',
                expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                features = None,
                remaining_activations = 56,
                message = ''
            )
        else:
            return LicenseValidationResponse(
                valid = True,
        )
        """

    def testLicenseValidationResponse(self):
        """Test LicenseValidationResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
