# coding: utf-8

"""
    License Management System

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.offline_activation_code_create import OfflineActivationCodeCreate

class TestOfflineActivationCodeCreate(unittest.TestCase):
    """OfflineActivationCodeCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OfflineActivationCodeCreate:
        """Test OfflineActivationCodeCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OfflineActivationCodeCreate`
        """
        model = OfflineActivationCodeCreate()
        if include_optional:
            return OfflineActivationCodeCreate(
                license_key_id = 56,
                machine_id = '',
                quantity = 56
            )
        else:
            return OfflineActivationCodeCreate(
                license_key_id = 56,
        )
        """

    def testOfflineActivationCodeCreate(self):
        """Test OfflineActivationCodeCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
