# coding: utf-8

"""
    License Management System

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.activations_api import ActivationsApi


class TestActivationsApi(unittest.TestCase):
    """ActivationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ActivationsApi()

    def tearDown(self) -> None:
        pass

    def test_deactivate_machine_api_v1_activations_activation_id_delete(self) -> None:
        """Test case for deactivate_machine_api_v1_activations_activation_id_delete

        Deactivate Machine
        """
        pass

    def test_get_license_activations_api_v1_activations_license_license_id_get(self) -> None:
        """Test case for get_license_activations_api_v1_activations_license_license_id_get

        Get License Activations
        """
        pass

    def test_list_activations_api_v1_activations_get(self) -> None:
        """Test case for list_activations_api_v1_activations_get

        List Activations
        """
        pass


if __name__ == '__main__':
    unittest.main()
