# coding: utf-8

"""
    License Management System

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.activation_form_create import ActivationFormCreate

class TestActivationFormCreate(unittest.TestCase):
    """ActivationFormCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ActivationFormCreate:
        """Test ActivationFormCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ActivationFormCreate`
        """
        model = ActivationFormCreate()
        if include_optional:
            return ActivationFormCreate(
                license_key = '',
                machine_id = '',
                machine_name = ''
            )
        else:
            return ActivationFormCreate(
                license_key = '',
                machine_id = '',
        )
        """

    def testActivationFormCreate(self):
        """Test ActivationFormCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
