# coding: utf-8

"""
    License Management System

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.validation_api import ValidationApi


class TestValidationApi(unittest.TestCase):
    """ValidationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ValidationApi()

    def tearDown(self) -> None:
        pass

    def test_license_heartbeat_api_v1_validation_heartbeat_post(self) -> None:
        """Test case for license_heartbeat_api_v1_validation_heartbeat_post

        License Heartbeat
        """
        pass

    def test_validate_license_api_v1_validation_post(self) -> None:
        """Test case for validate_license_api_v1_validation_post

        Validate License
        """
        pass


if __name__ == '__main__':
    unittest.main()
