# coding: utf-8

"""
    License Management System

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.license_validation_request import LicenseValidationRequest

class TestLicenseValidationRequest(unittest.TestCase):
    """LicenseValidationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LicenseValidationRequest:
        """Test LicenseValidationRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LicenseValidationRequest`
        """
        model = LicenseValidationRequest()
        if include_optional:
            return LicenseValidationRequest(
                license_key = '',
                machine_id = ''
            )
        else:
            return LicenseValidationRequest(
                license_key = '',
                machine_id = '',
        )
        """

    def testLicenseValidationRequest(self):
        """Test LicenseValidationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
