# coding: utf-8

"""
    License Management System

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.activation_forms_api import ActivationFormsApi


class TestActivationFormsApi(unittest.TestCase):
    """ActivationFormsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ActivationFormsApi()

    def tearDown(self) -> None:
        pass

    def test_complete_activation_form_api_v1_activation_forms_complete_post(self) -> None:
        """Test case for complete_activation_form_api_v1_activation_forms_complete_post

        Complete Activation Form
        """
        pass

    def test_create_activation_form_api_v1_activation_forms_post(self) -> None:
        """Test case for create_activation_form_api_v1_activation_forms_post

        Create Activation Form
        """
        pass

    def test_generate_offline_codes_api_v1_activation_forms_offline_codes_post(self) -> None:
        """Test case for generate_offline_codes_api_v1_activation_forms_offline_codes_post

        Generate Offline Codes
        """
        pass

    def test_get_activation_form_api_v1_activation_forms_form_id_get(self) -> None:
        """Test case for get_activation_form_api_v1_activation_forms_form_id_get

        Get Activation Form
        """
        pass

    def test_list_activation_forms_api_v1_activation_forms_get(self) -> None:
        """Test case for list_activation_forms_api_v1_activation_forms_get

        List Activation Forms
        """
        pass


if __name__ == '__main__':
    unittest.main()
