# coding: utf-8

"""
    License Management System

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.applications_api import ApplicationsApi


class TestApplicationsApi(unittest.TestCase):
    """ApplicationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ApplicationsApi()

    def tearDown(self) -> None:
        pass

    def test_create_application_api_v1_applications_post(self) -> None:
        """Test case for create_application_api_v1_applications_post

        Create Application
        """
        pass

    def test_delete_application_api_v1_applications_application_id_delete(self) -> None:
        """Test case for delete_application_api_v1_applications_application_id_delete

        Delete Application
        """
        pass

    def test_get_application_api_v1_applications_application_id_get(self) -> None:
        """Test case for get_application_api_v1_applications_application_id_get

        Get Application
        """
        pass

    def test_list_applications_api_v1_applications_get(self) -> None:
        """Test case for list_applications_api_v1_applications_get

        List Applications
        """
        pass

    def test_update_application_api_v1_applications_application_id_put(self) -> None:
        """Test case for update_application_api_v1_applications_application_id_put

        Update Application
        """
        pass


if __name__ == '__main__':
    unittest.main()
