# coding: utf-8

"""
    License Management System

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.customers_api import CustomersApi


class TestCustomersApi(unittest.TestCase):
    """CustomersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CustomersApi()

    def tearDown(self) -> None:
        pass

    def test_create_customer_api_v1_customers_post(self) -> None:
        """Test case for create_customer_api_v1_customers_post

        Create Customer
        """
        pass

    def test_delete_customer_api_v1_customers_customer_id_delete(self) -> None:
        """Test case for delete_customer_api_v1_customers_customer_id_delete

        Delete Customer
        """
        pass

    def test_get_customer_api_v1_customers_customer_id_get(self) -> None:
        """Test case for get_customer_api_v1_customers_customer_id_get

        Get Customer
        """
        pass

    def test_list_customers_api_v1_customers_get(self) -> None:
        """Test case for list_customers_api_v1_customers_get

        List Customers
        """
        pass

    def test_update_customer_api_v1_customers_customer_id_put(self) -> None:
        """Test case for update_customer_api_v1_customers_customer_id_put

        Update Customer
        """
        pass


if __name__ == '__main__':
    unittest.main()
