version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: licensing-postgres-dev
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - licensing_server_postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - postgres-network
    restart: unless-stopped

volumes:
  licensing_server_postgres_data:
    driver: local

networks:
  postgres-network:
    driver: bridge
