# coding: utf-8

"""
    License Management System

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.license_status import LicenseStatus
from typing import Optional, Set
from typing_extensions import Self

class LicenseValidationResponse(BaseModel):
    """
    LicenseValidationResponse
    """ # noqa: E501
    valid: StrictBool
    license_id: Optional[StrictInt] = None
    customer_id: Optional[StrictInt] = None
    application_id: Optional[StrictInt] = None
    status: Optional[LicenseStatus] = None
    expires_at: Optional[datetime] = None
    features: Optional[Dict[str, Any]] = None
    remaining_activations: Optional[StrictInt] = None
    message: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["valid", "license_id", "customer_id", "application_id", "status", "expires_at", "features", "remaining_activations", "message"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LicenseValidationResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if license_id (nullable) is None
        # and model_fields_set contains the field
        if self.license_id is None and "license_id" in self.model_fields_set:
            _dict['license_id'] = None

        # set to None if customer_id (nullable) is None
        # and model_fields_set contains the field
        if self.customer_id is None and "customer_id" in self.model_fields_set:
            _dict['customer_id'] = None

        # set to None if application_id (nullable) is None
        # and model_fields_set contains the field
        if self.application_id is None and "application_id" in self.model_fields_set:
            _dict['application_id'] = None

        # set to None if status (nullable) is None
        # and model_fields_set contains the field
        if self.status is None and "status" in self.model_fields_set:
            _dict['status'] = None

        # set to None if expires_at (nullable) is None
        # and model_fields_set contains the field
        if self.expires_at is None and "expires_at" in self.model_fields_set:
            _dict['expires_at'] = None

        # set to None if features (nullable) is None
        # and model_fields_set contains the field
        if self.features is None and "features" in self.model_fields_set:
            _dict['features'] = None

        # set to None if remaining_activations (nullable) is None
        # and model_fields_set contains the field
        if self.remaining_activations is None and "remaining_activations" in self.model_fields_set:
            _dict['remaining_activations'] = None

        # set to None if message (nullable) is None
        # and model_fields_set contains the field
        if self.message is None and "message" in self.model_fields_set:
            _dict['message'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LicenseValidationResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "valid": obj.get("valid"),
            "license_id": obj.get("license_id"),
            "customer_id": obj.get("customer_id"),
            "application_id": obj.get("application_id"),
            "status": obj.get("status"),
            "expires_at": obj.get("expires_at"),
            "features": obj.get("features"),
            "remaining_activations": obj.get("remaining_activations"),
            "message": obj.get("message")
        })
        return _obj


