# coding: utf-8

"""
    License Management System

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class OfflineActivationCodeResponse(BaseModel):
    """
    OfflineActivationCodeResponse
    """ # noqa: E501
    id: StrictInt
    license_key_id: StrictInt
    activation_code: StrictStr
    machine_id: Optional[StrictStr]
    is_used: StrictBool
    expires_at: datetime
    created_at: datetime
    used_at: Optional[datetime]
    __properties: ClassVar[List[str]] = ["id", "license_key_id", "activation_code", "machine_id", "is_used", "expires_at", "created_at", "used_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OfflineActivationCodeResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if machine_id (nullable) is None
        # and model_fields_set contains the field
        if self.machine_id is None and "machine_id" in self.model_fields_set:
            _dict['machine_id'] = None

        # set to None if used_at (nullable) is None
        # and model_fields_set contains the field
        if self.used_at is None and "used_at" in self.model_fields_set:
            _dict['used_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OfflineActivationCodeResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "license_key_id": obj.get("license_key_id"),
            "activation_code": obj.get("activation_code"),
            "machine_id": obj.get("machine_id"),
            "is_used": obj.get("is_used"),
            "expires_at": obj.get("expires_at"),
            "created_at": obj.get("created_at"),
            "used_at": obj.get("used_at")
        })
        return _obj


