# coding: utf-8

"""
    License Management System

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class TokenScope(str, Enum):
    """
    TokenScope
    """

    """
    allowed enum values
    """
    LICENSE_COLON_READ = 'license:read'
    LICENSE_COLON_WRITE = 'license:write'
    LICENSE_COLON_DELETE = 'license:delete'
    CUSTOMER_COLON_READ = 'customer:read'
    CUSTOMER_COLON_WRITE = 'customer:write'
    CUSTOMER_COLON_DELETE = 'customer:delete'
    APPLICATION_COLON_READ = 'application:read'
    APPLICATION_COLON_WRITE = 'application:write'
    APPLICATION_COLON_DELETE = 'application:delete'
    ACTIVATION_COLON_READ = 'activation:read'
    ACTIVATION_COLON_WRITE = 'activation:write'
    ACTIVATION_COLON_DELETE = 'activation:delete'
    VALIDATION = 'validation'
    USER_COLON_MANAGEMENT = 'user:management'
    TOKEN_COLON_MANAGEMENT = 'token:management'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TokenScope from a JSON string"""
        return cls(json.loads(json_str))


