# -*- coding: utf-8 -*-
"""
Data models for license server client SDK.
Adapted from original Cryptolens implementation for our licensing server.
"""
import json
import base64
import datetime
import copy
import xml.etree.ElementTree

from .internal import LicenseServerHelpers

class ActivatedMachine:
    """Represents a machine that has activated a license."""
    def __init__(self, IP, Mid, Time, FriendlyName="", FloatingExpires=""):
        self.IP = IP
        self.Mid = Mid
        self.Time = Time
        self.FriendlyName = FriendlyName
        self.FloatingExpires = FloatingExpires

class LicenseKey:
    """Represents a license key with all its properties."""
    
    def __init__(self, ProductId, ID, Key, Created, Expires, Period, Notes, Block, GlobalId, Customer, 
                 ActivatedMachines, TrialActivation, MaxNoOfMachines, 
                 AllowedMachines, DataObjects, SignDate, RawResponse):
        
        self.product_id = ProductId
        self.id = ID
        self.key = Key
        self.created = Created
        self.expires = Expires
        self.period = Period
        self.notes = Notes
        self.block = Block
        self.global_id = GlobalId
        self.customer = Customer
        self.activated_machines = ActivatedMachines
        self.trial_activation = TrialActivation
        self.max_no_of_machines = MaxNoOfMachines
        self.allowed_machines = AllowedMachines
        self.data_objects = DataObjects
        self.sign_date = SignDate
        self.raw_response = RawResponse
        
    @staticmethod
    def from_response(response):
        """Create a LicenseKey from a response object."""
        if response.result == 1:
            raise ValueError("The response did not contain any license key object since it was unsuccessful. Message '{0}'.".format(response.message))
        
        obj = json.loads(base64.b64decode(response.license_key).decode('utf-8'))
        
        try:
            datetime.datetime.fromtimestamp(obj["Expires"])
        except: 
            raise ValueError("The expiration date cannot be converted to a datetime object. Please try setting the period to a lower value.")

        return LicenseKey(obj["ProductId"], obj["ID"], obj["Key"], datetime.datetime.fromtimestamp(obj["Created"]),
                          datetime.datetime.fromtimestamp(obj["Expires"]), obj["Period"], obj["Notes"], obj["Block"], obj["GlobalId"],
                          obj["Customer"], LicenseKey.__load_activated_machines(obj["ActivatedMachines"]), obj["TrialActivation"], 
                          obj["MaxNoOfMachines"], obj["AllowedMachines"], obj["DataObjects"], 
                          datetime.datetime.fromtimestamp(obj["SignDate"]), response)
        
    def save_as_string(self):
        """Save the license as a string that can later be read by load_from_string."""
        res = copy.copy(self.raw_response.__dict__)
        res["licenseKey"] = res["license_key"]
        res.pop("license_key", None)
        return json.dumps(res)
    
    @staticmethod
    def load_from_string(rsa_pub_key, string, signature_expiration_interval=-1):
        """Load a license from a string generated by save_as_string."""
        response = Response("", "", "", "")
        
        try:
            response = Response.from_string(string)
        except Exception as ex:
            return None
        
        if response.result == "1":
            return None
        else:
            try:
                pub_key = RSAPublicKey.from_string(rsa_pub_key)
                if LicenseServerHelpers.verify_signature(response, pub_key):
                    license_key = LicenseKey.from_response(response)
                    
                    if signature_expiration_interval > 0 and \
                    (license_key.sign_date + datetime.timedelta(days=1*signature_expiration_interval) < datetime.datetime.utcnow()):
                        return None
                    
                    return license_key
                else:
                    return None
            except Exception:
                return None
      
    @staticmethod
    def __load_activated_machines(obj):
        """Load activated machines from response object."""
        if obj is None:
            return None
        
        arr = []
        for item in obj:
            arr.append(ActivatedMachine(**item))
        
        return arr

class Response:
    """Represents a response from the license server."""
    
    def __init__(self, license_key, signature, result, message, metadata=None):
        self.license_key = license_key
        self.signature = signature
        self.result = result
        self.message = message
        self.metadata = metadata
        
    @staticmethod
    def from_string(response_string):        
        """Create a Response from a JSON string."""
        obj = dict((k.lower(), v) for k, v in json.loads(response_string).items())
        
        license_key = ""
        signature = ""
        result = 0
        message = ""
        metadata = None
        
        if "licensekey" in obj:
            license_key = obj["licensekey"]
            
        if "signature" in obj:
            signature = obj["signature"]
        
        if "message" in obj:
            message = obj["message"]
            
        if "result" in obj:
            result = obj["result"]
        else:
            result = 1
            
        if "metadata" in obj:
            metadata = obj["metadata"]
            
        return Response(license_key, signature, result, message, metadata)

    @staticmethod
    def from_dict(response_dict):
        """Create a Response from a dictionary."""
        return Response(
            license_key=response_dict.get("license_key", ""),
            signature=response_dict.get("signature", ""),
            result=response_dict.get("result", 0),
            message=response_dict.get("message", ""),
            metadata=response_dict.get("metadata")
        )
        
class RSAPublicKey:
    """Represents an RSA public key for signature verification."""
    
    def __init__(self, modulus, exponent):
        self.modulus = modulus
        self.exponent = exponent
        
    @staticmethod
    def from_string(rsa_pub_key_string):
        """Create an RSAPublicKey from an XML string."""
        rsa_key = xml.etree.ElementTree.fromstring(rsa_pub_key_string)
        return RSAPublicKey(rsa_key.find('Modulus').text, rsa_key.find('Exponent').text)