# coding: utf-8

# flake8: noqa

"""
    License Management System

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "ActivationFormsApi",
    "ActivationsApi",
    "ApplicationsApi",
    "AuthenticationApi",
    "CustomersApi",
    "LicensesApi",
    "ValidationApi",
    "DefaultApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "APITokenCreate",
    "APITokenCreateResponse",
    "APITokenResponse",
    "APITokenUpdate",
    "ActivationFormComplete",
    "ActivationFormCreate",
    "ActivationFormResponse",
    "ActivationResponse",
    "ActivationStatus",
    "ApplicationCreate",
    "ApplicationResponse",
    "ApplicationUpdate",
    "CustomerCreate",
    "CustomerResponse",
    "CustomerUpdate",
    "HTTPValidationError",
    "LicenseKeyCreate",
    "LicenseKeyResponse",
    "LicenseKeyUpdate",
    "LicenseStatus",
    "LicenseValidationRequest",
    "LicenseValidationResponse",
    "OfflineActivationCodeCreate",
    "OfflineActivationCodeResponse",
    "SystemRole",
    "TokenResponse",
    "TokenScope",
    "UserBusinessRoleUpdate",
    "UserChangePassword",
    "UserCreate",
    "UserLogin",
    "UserResponse",
    "UserRole",
    "UserSystemRoleUpdate",
    "UserUpdate",
    "ValidationError",
    "ValidationErrorLocInner",
]

# import apis into sdk package
from openapi_client.api.activation_forms_api import ActivationFormsApi as ActivationFormsApi
from openapi_client.api.activations_api import ActivationsApi as ActivationsApi
from openapi_client.api.applications_api import ApplicationsApi as ApplicationsApi
from openapi_client.api.authentication_api import AuthenticationApi as AuthenticationApi
from openapi_client.api.customers_api import CustomersApi as CustomersApi
from openapi_client.api.licenses_api import LicensesApi as LicensesApi
from openapi_client.api.validation_api import ValidationApi as ValidationApi
from openapi_client.api.default_api import DefaultApi as DefaultApi

# import ApiClient
from openapi_client.api_response import ApiResponse as ApiResponse
from openapi_client.api_client import ApiClient as ApiClient
from openapi_client.configuration import Configuration as Configuration
from openapi_client.exceptions import OpenApiException as OpenApiException
from openapi_client.exceptions import ApiTypeError as ApiTypeError
from openapi_client.exceptions import ApiValueError as ApiValueError
from openapi_client.exceptions import ApiKeyError as ApiKeyError
from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from openapi_client.models.api_token_create import APITokenCreate as APITokenCreate
from openapi_client.models.api_token_create_response import APITokenCreateResponse as APITokenCreateResponse
from openapi_client.models.api_token_response import APITokenResponse as APITokenResponse
from openapi_client.models.api_token_update import APITokenUpdate as APITokenUpdate
from openapi_client.models.activation_form_complete import ActivationFormComplete as ActivationFormComplete
from openapi_client.models.activation_form_create import ActivationFormCreate as ActivationFormCreate
from openapi_client.models.activation_form_response import ActivationFormResponse as ActivationFormResponse
from openapi_client.models.activation_response import ActivationResponse as ActivationResponse
from openapi_client.models.activation_status import ActivationStatus as ActivationStatus
from openapi_client.models.application_create import ApplicationCreate as ApplicationCreate
from openapi_client.models.application_response import ApplicationResponse as ApplicationResponse
from openapi_client.models.application_update import ApplicationUpdate as ApplicationUpdate
from openapi_client.models.customer_create import CustomerCreate as CustomerCreate
from openapi_client.models.customer_response import CustomerResponse as CustomerResponse
from openapi_client.models.customer_update import CustomerUpdate as CustomerUpdate
from openapi_client.models.http_validation_error import HTTPValidationError as HTTPValidationError
from openapi_client.models.license_key_create import LicenseKeyCreate as LicenseKeyCreate
from openapi_client.models.license_key_response import LicenseKeyResponse as LicenseKeyResponse
from openapi_client.models.license_key_update import LicenseKeyUpdate as LicenseKeyUpdate
from openapi_client.models.license_status import LicenseStatus as LicenseStatus
from openapi_client.models.license_validation_request import LicenseValidationRequest as LicenseValidationRequest
from openapi_client.models.license_validation_response import LicenseValidationResponse as LicenseValidationResponse
from openapi_client.models.offline_activation_code_create import OfflineActivationCodeCreate as OfflineActivationCodeCreate
from openapi_client.models.offline_activation_code_response import OfflineActivationCodeResponse as OfflineActivationCodeResponse
from openapi_client.models.system_role import SystemRole as SystemRole
from openapi_client.models.token_response import TokenResponse as TokenResponse
from openapi_client.models.token_scope import TokenScope as TokenScope
from openapi_client.models.user_business_role_update import UserBusinessRoleUpdate as UserBusinessRoleUpdate
from openapi_client.models.user_change_password import UserChangePassword as UserChangePassword
from openapi_client.models.user_create import UserCreate as UserCreate
from openapi_client.models.user_login import UserLogin as UserLogin
from openapi_client.models.user_response import UserResponse as UserResponse
from openapi_client.models.user_role import UserRole as UserRole
from openapi_client.models.user_system_role_update import UserSystemRoleUpdate as UserSystemRoleUpdate
from openapi_client.models.user_update import UserUpdate as UserUpdate
from openapi_client.models.validation_error import ValidationError as ValidationError
from openapi_client.models.validation_error_loc_inner import ValidationErrorLocInner as ValidationErrorLocInner
